# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsSync < Formula
  desc "hecks dns records are in sync with expected value"
  homepage "https://github.com/chandanpasunoori/dns-sync"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chandanpasunoori/dns-sync/releases/download/0.0.6/dns-sync_0.0.6_darwin_arm64.tar.gz"
      sha256 "bd8372e04acfb304b9654307c7ab4c4ca416441a5a60ee960cb8fbccbcb8a6c5"

      def install
        bin.install "dns-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/dns-sync/releases/download/0.0.6/dns-sync_0.0.6_darwin_amd64v2.tar.gz"
      sha256 "fb9afbf0f82ec5054bdb3ef0c2eaf48f2adb704d5ce5dc6e6426a6d625078a3e"

      def install
        bin.install "dns-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chandanpasunoori/dns-sync/releases/download/0.0.6/dns-sync_0.0.6_linux_arm64.tar.gz"
      sha256 "375a2911c9050a32faa3f784d0f362baba7fb5b58910d277c0a7c53c6bf33240"

      def install
        bin.install "dns-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/dns-sync/releases/download/0.0.6/dns-sync_0.0.6_linux_amd64v2.tar.gz"
      sha256 "cb5a63b2a4a064d31464eddd2da08afc440030e1219d8c925ca3f163b6567247"

      def install
        bin.install "dns-sync"
      end
    end
  end
end
