# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsCheck < Formula
  desc "Syncs dns records from active instances to dns zone"
  homepage "https://github.com/chandanpasunoori/dns-check"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chandanpasunoori/dns-check/releases/download/0.0.10/dns-check_0.0.10_darwin_arm64.tar.gz"
      sha256 "93617624eaeca04ef3b4f2fc71d98117136bd0b733b99d512374afa779216bef"

      def install
        bin.install "dns-check"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/dns-check/releases/download/0.0.10/dns-check_0.0.10_darwin_amd64v2.tar.gz"
      sha256 "ecc353f7d8bed570dff05b0811617a6ebbc5686f767b49081bc50f490061bb46"

      def install
        bin.install "dns-check"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chandanpasunoori/dns-check/releases/download/0.0.10/dns-check_0.0.10_linux_arm64.tar.gz"
      sha256 "3367b5d1c0e074e51dea23c775af8b28712b7afce8d988c35a5c7ecf3c5169d2"

      def install
        bin.install "dns-check"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/dns-check/releases/download/0.0.10/dns-check_0.0.10_linux_amd64v2.tar.gz"
      sha256 "3dc6a3d86c1b79db50393cd697375baf742398fe9fdd8b10566e239622cf30e6"

      def install
        bin.install "dns-check"
      end
    end
  end
end
