# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kail < Formula
  desc "kubernetes tail - pod log viewer"
  homepage "https://github.com/chandanpasunoori/kail"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_darwin_arm64.tar.gz"
      sha256 "7dccdfffebd2b5917a1335109bf05b6268979803193ed9be1aadd8a91452c75b"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_darwin_amd64v2.tar.gz"
      sha256 "d3d41ddd700cd99daede4b01080550493def12f26b8954be9e22566073359756"

      def install
        bin.install "kail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_linux_armv6.tar.gz"
      sha256 "39db21d922358d856499aac5bca25222637e6e4d2d8f86f69f94053fe439de02"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_linux_arm64.tar.gz"
      sha256 "29e60df9f1086dcb474b416a25fac80aa5065221cbf8d9c8f8ede6d54ac5901b"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_linux_amd64v2.tar.gz"
      sha256 "3b20ddc5e3b91ee03bd36d6f2473305ed9243e974d0a7a609f58d30a68b803f1"

      def install
        bin.install "kail"
      end
    end
  end
end
