# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kail < Formula
  desc "kubernetes tail - pod log viewer"
  homepage "https://github.com/chandanpasunoori/kail"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_darwin_arm64.tar.gz"
      sha256 "8b754415c3fbf25aad5731911a10b9bacc13de88055a1615538ed0775ae3325e"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_darwin_amd64v2.tar.gz"
      sha256 "56c1f8a1cb4e46541b7211118d81effe28a3b6ee0d970d35cf67d3a92c1bb538"

      def install
        bin.install "kail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_linux_armv6.tar.gz"
      sha256 "d4231c9e3974817295a6716afa17c678349690ef30fc21c2451c753fb11923fc"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_linux_arm64.tar.gz"
      sha256 "3776c7581433bb1809909ae0727e767c995fff5310ef55f4ed0ad388e49385d1"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chandanpasunoori/kail/releases/download/v0.16.0/kail_0.16.0_linux_amd64v2.tar.gz"
      sha256 "33149f1e98b3843127c53e3a8f28adc6614f6085132be703ea799a55b214788e"

      def install
        bin.install "kail"
      end
    end
  end
end
