# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kail < Formula
  desc "kubernetes tail - pod log viewer"
  homepage "https://github.com/chandanpasunoori/kail"
  version "0.17.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/boz/kail/releases/download/v0.17.4/kail_v0.17.4_darwin_arm64.tar.gz"
      sha256 "61c331113e3cdc40133f4b5f7a200862e281c23af3f6017bb71a71bae83b0caa"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boz/kail/releases/download/v0.17.4/kail_v0.17.4_darwin_amd64v2.tar.gz"
      sha256 "88f2f514760312d2f029e69e733575b65563c08f38f6e238f1f2bcc7f57fd661"

      def install
        bin.install "kail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boz/kail/releases/download/v0.17.4/kail_v0.17.4_linux_arm64.tar.gz"
      sha256 "c29c6e69b2ed1a8d8ae1ce00bf5857d2984c820c5c3b83bac9b9f04bc4b372d3"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boz/kail/releases/download/v0.17.4/kail_v0.17.4_linux_amd64v2.tar.gz"
      sha256 "aebdf0401a46b26189eeec2cdd8539675805fcfa68a4561c9ae1993f275c3358"

      def install
        bin.install "kail"
      end
    end
  end
end
