# This file was generated by GoReleaser. DO NOT EDIT.
cask "version" do
  name "version"
  desc "Git version tag generator CLI"
  homepage "https://github.com/chandanpasunoori/version"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "version"

  on_macos do
    on_intel do
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_darwin_amd64.tar.gz"
      sha256 "35813a98b74d9926fc7b9bbcf3124b10af77b463ccd83e1331f596a8deef9759"
    end
    on_arm do
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_darwin_arm64.tar.gz"
      sha256 "b89a5b1ccee02876b24adf744cee674b7747614d85d43195d6dc0c4d6b89fff6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_linux_amd64.tar.gz"
      sha256 "c7c1db2714dea2d9abada0db0cebd493a4b8fb4c4ea6641cd33ac4b48b2e3611"
    end
    on_arm do
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_linux_arm64.tar.gz"
      sha256 "0b79d8ad7baa054527d5ec24db008d254c768c10bcc412ba3b386748fb87203b"
    end
  end

  # No zap stanza required
end
