# This file was generated by GoReleaser. DO NOT EDIT.
cask "version" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "12021a2ee30289873a3452337f549044e530b92a5f81be40e4d2fd03fe57db22"
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "42f1e603c89c14459c37a3e8f154eaec9ea159143e7e7406c67ab0f8a07e9aa3"
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d7e446014826496ec75629127d8f6d1537fe17697145f39f2e70988a38f93e40"
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3aa32b6a45e105d820f7ea23741ce54f9ac1851f9dd2a362cfca7742d7037a6d"
      url "https://github.com/chandanpasunoori/version/releases/download/v#{version}/version_linux_amd64.tar.gz"
    end
  end

  name "version"
  desc "Git version tag generator CLI"
  homepage "https://github.com/chandanpasunoori/version"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "version"

  # No zap stanza required
end
